    <style>
        #addedAlert {
            display: grid;
            align-items: center;
            justify-items: center;
            background-color: #ccc;
            margin-top: 40px;
            width: 250px;
            height: 70px;
            opacity: 0.8;
            border-radius: 10px;
            font-size: 35px;
            text-align: center;
            transition: opacity 0.5s;
        }
        #alertContainer{
            z-index: 10;
            pointer-events: none;
            position: absolute;
            top: 0px;
            left: 0px;
            right: 0px;
            bottom: 0px;
            display: grid;
            align-items: center;
            justify-items: center;
        }
    </style>

    <div id="alertContainer">
        <div id="addedAlert">
            // Content generated by code
        </div>
    </div>

    <script>
        function showOverlay(msg) {
            const addedAlert = document.getElementById("addedAlert");
            addedAlert.innerHTML = msg;
            window.setTimeout(() => {
                addedAlert.style.opacity = "0";
            }, 1000);
        }

        showOverlay("Item added!");
    </script>
